research_task:
  description: >
    Utilize sua ferramenta para buscar {residencia} disponíveis para aluguel em Campinas - SP.
    Os imóveis devem ser casas ou apartamentos com aluguel de até R${valor}/mês.
    A busca deve ser feita no portal ZapImóveis.
    
    Dê preferência para os imóveis com mais informações disponíveis como: valor, bairro, tipo, e link para o anúncio.
  expected_output: >
    Uma lista de pelo menos 5 imóveis com: tipo, valor, bairro (se disponível) e link direto para o anúncio.
  agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
